spring.application.name=springsecurity

logging.level.root=error
logging.level.com.springsecurity=info

spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasour ce.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#spring.security.oauth2.client.registration.github.client-id={{ github_client-id }}
#spring.security.oauth2.client.registration.github.client-secret={{ github_client-secret }}

#spring.security.oauth2.client.registration.google.client-id={{ google_client-id }}
#spring.security.oauth2.client.registration.google.client-secret={{ google_client-secret}}